### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by cj-neo** [Quan666/PikPakAPI#45]
好像是官方不支援 oauth2 認證了，可以幫忙看一下嗎？ 

錯誤訊息：

Traceback (most recent call last):
  File "D:\Projects\python\pikpak\fix.py", line 508, in main
    await pp.login()
  File "D:\Projects\python\pikpak\pikpakapi\__init__.py", line 183, in login        
    user_info = await self._request_post(
  File "D:\Projects\python\pikpak\pikpakapi\__init__.py", line 123, in _request_post
    return await self._make_request("post", url, data=data, headers=headers)        
  File "D:\Projects\python\pikpak\pikpakapi\__init__.py", line 106, in _make_request
    raise PikpakException(f"{json_data['error_description']}")
pikpakapi.PikpakException.PikpakException: currently not supported

我發現 alist 那邊好像改好了，可參考這邊 https://github.com/alist-org/alist/pull/7017

謝謝！

**Comment by Quan666** [comment]
#44 已经解决
