### ISSUE TITLE
跑test.py登录不上,用的login branch

### ISSUE THREAD

**Issue by weibaozi** [Quan666/PikPakAPI#49]
ERROR:root:All connection attempts failed
ERROR:root:All connection attempts failed
ERROR:root:All connection attempts failed
Traceback (most recent call last):
  File "g:\study\others\Anipik\PikPakAPI-login\test.py", line 85, in <module>
    asyncio.run(test())
  File "C:\ProgramData\anaconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete       
    return future.result()
           ^^^^^^^^^^^^^^^
  File "g:\study\others\Anipik\PikPakAPI-login\test.py", line 18, in test
    await client.login()
  File "g:\study\others\Anipik\PikPakAPI-login\pikpakapi\__init__.py", line 265, in login
    result = await self.captcha_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\study\others\Anipik\PikPakAPI-login\pikpakapi\__init__.py", line 249, in captcha_init    
    return await self._request_post(url, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\study\others\Anipik\PikPakAPI-login\pikpakapi\__init__.py", line 194, in _request_post   
    return await self._make_request("post", url, data=data, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\study\others\Anipik\PikPakAPI-login\pikpakapi\__init__.py", line 179, in _make_request   
    raise PikpakException(error_decription)
pikpakapi.PikpakException.PikpakException

**Comment by Quan666** [comment]
你网络有问题？

**Comment by weibaozi** [comment]
> 你网络有问题？

不应该吧我正常客户端都可以登录，也不需要验证啥的

**Comment by Quan666** [comment]
这个错误就是网络有问题导致

**Comment by wheezy1749** [comment]
Same thing started happening to me. Running debugger on the code I got the actual response. Sorry, only speak English and using translate.

```
{
'error': 'captcha_invalid', 
'error_code': 4002, 
'error_description': 'Aborted - Your operation is too frequent, please try again later',
'details': [{...}, {...}]
}
```

Would be nice to print the error_description object in the exception. Right nows its only printing it if it's code 16.

**Comment by njki** [comment]
请问你解决了吗? 我也有同样的问题, 无论流量还是宽带, 无论是否挂梯子.

**Comment by Quan666** [comment]
还不行的话，自己抓包网页上的 refresh_token
写到代码里面
