### ISSUE TITLE
执行test.py报错

### ISSUE THREAD

**Issue by ftufkc** [Quan666/PikPakAPI#9]
(base) ➜  PikPakAPI-main python --version
Python 3.9.13

(base) ➜  PikPakAPI-main python test.py  
Traceback (most recent call last):
  File "/Users/XXX/Downloads/Chrome/PikPakAPI-main/test.py", line 37, in <module>
    asyncio.run(test())
  File "/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/XXX/Downloads/Chrome/PikPakAPI-main/test.py", line 13, in test
    print(json.dumps(await client.get_user_info(), indent=4))
TypeError: object dict can't be used in 'await' expression

**Comment by Quan666** [comment]
await client.get_user_info() 把前面的 await 删掉就好
